# Generated by Django 5.2.6 on 2025-10-27 16:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('summary', models.TextField(blank=True, max_length=200, verbose_name='摘要')),
                ('content', models.TextField(verbose_name='内容')),
                ('tags', models.JSONField(default=list, verbose_name='标签')),
                ('category', models.CharField(choices=[('technology', '技术'), ('life', '生活'), ('design', '设计'), ('other', '其他')], default='technology', max_length=20, verbose_name='分类')),
                ('visibility', models.CharField(choices=[('public', '公开'), ('private', '私密')], default='public', max_length=10, verbose_name='可见性')),
                ('is_draft', models.BooleanField(default=False, verbose_name='是否为草稿')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='发布时间')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='作者')),
            ],
            options={
                'verbose_name': '博客',
                'verbose_name_plural': '博客',
                'ordering': ['-created_at'],
            },
        ),
    ]
