# Generated by Django 5.2.6 on 2025-10-27 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appone', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webinfo',
            name='web_name',
            field=models.CharField(default='', max_length=16, verbose_name='网站名称'),
        ),
    ]
