# Generated by Django 5.2.6 on 2025-11-14 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appone', '0002_alter_webinfo_web_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='code_used_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='序列号使用时间'),
        ),
        migrations.AddField(
            model_name='client',
            name='registration_code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='注册序列号'),
        ),
        migrations.AlterField(
            model_name='client',
            name='province',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
