# Generated by Django 5.2.6 on 2026-08-05 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appone', '0003_client_code_used_at_client_registration_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='任务标题')),
                ('description', models.TextField(blank=True, null=True, verbose_name='任务描述')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='任务总金额')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='剩余金额')),
                ('max_participants', models.IntegerField(default=0, verbose_name='最大参与人数(0为不限)')),
                ('completed_count', models.IntegerField(default=0, verbose_name='已完成人数')),
                ('status', models.SmallIntegerField(choices=[(0, '进行中'), (1, '已完成'), (2, '已关闭')], default=0, verbose_name='任务状态')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='最终修改时间')),
                ('deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_tasks', to='appone.client', verbose_name='发布者')),
            ],
            options={
                'verbose_name': '任务表',
                'verbose_name_plural': '任务表',
                'db_table': 'task',
            },
        ),
        migrations.CreateModel(
            name='TaskParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.SmallIntegerField(choices=[(0, '已参与'), (1, '待审核'), (2, '已完成'), (3, '已驳回')], default=0, verbose_name='参与状态')),
                ('proof', models.URLField(blank=True, max_length=256, null=True, verbose_name='凭证图片')),
                ('reward', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='获得奖励')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='参与时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='最终修改时间')),
                ('deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='task.task', verbose_name='任务')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_participations', to='appone.client', verbose_name='参与用户')),
            ],
            options={
                'verbose_name': '任务参与者表',
                'verbose_name_plural': '任务参与者表',
                'db_table': 'task_participant',
                'unique_together': {('task', 'user')},
            },
        ),
        migrations.CreateModel(
            name='TaskProof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.URLField(max_length=256, verbose_name='凭证图片地址')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proofs', to='task.taskparticipant', verbose_name='参与记录')),
            ],
            options={
                'verbose_name': '任务凭证表',
                'verbose_name_plural': '任务凭证表',
                'db_table': 'task_proof',
            },
        ),
    ]
