# Generated by Django 5.2.6 on 2025-11-14 16:37

import godot.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarkdownDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='输入文档的标题', max_length=200, verbose_name='文档标题')),
                ('description', models.TextField(blank=True, help_text='对文档的简要描述', verbose_name='文档描述')),
                ('file', models.FileField(help_text='选择本地的Markdown文件', upload_to=godot.models.markdown_file_upload_path, validators=[godot.models.validate_markdown_file_extension], verbose_name='Markdown文件')),
                ('is_previewable', models.BooleanField(default=True, help_text='控制Vue前端是否可以加载和预览此文档', verbose_name='允许预览')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('file_size', models.PositiveIntegerField(default=0, help_text='自动计算的文件大小', verbose_name='文件大小(字节)')),
            ],
            options={
                'verbose_name': 'Markdown文档',
                'verbose_name_plural': 'Markdown文档',
                'ordering': ['-created_at'],
            },
        ),
    ]
