# Generated by Django 5.2.6 on 2025-11-14 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('godot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='markdowndocument',
            name='file_encoding',
            field=models.CharField(default='utf-8', help_text='自动检测的文件编码', max_length=20, verbose_name='文件编码'),
        ),
    ]
