"""
Django settings for luntan project.

Generated by 'django-admin startproject' using Django 4.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path
import logging

# 邮箱服务 start
#from_address = 'monkey-papa@qq.com' # 你的邮箱
#wand = "monkey-papa" # 邮箱秘钥

from_address = 'yiqiu1996@163.com' # 你的邮箱
wand = "fang1937@" # 邮箱秘钥
# 邮箱服务 end



# 对于 163 邮箱的正确配置
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.163.com'
EMAIL_PORT = 465  # 或者 994，163邮箱推荐使用465端口
EMAIL_USE_SSL = True  # 重要！163邮箱使用SSL，不是TLS
EMAIL_HOST_USER = 'yiqiu1996@163.com'  # 完整的163邮箱地址
EMAIL_HOST_PASSWORD = 'WFg5e3s8dUSi9Rc8'  # 不是邮箱密码，是SMTP授权码
DEFAULT_FROM_EMAIL = 'yiqiu1996@163.com'  # 默认发件人

from django.conf import settings
email_host_user = settings.EMAIL_HOST_USER


# ai摘要
summary_url = "http://monkey-papa.com"
summary_authorization = "application-12345678"

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# 項目基礎路徑
BASE_DIR = Path(__file__).resolve().parent.parent

#deepseek增加的圖片存儲路徑
# 媒體文件配置 - 必須設置！
import os  # 添加這行！
MEDIA_URL = '/media/'  # URL前綴
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')  # 服務器存儲路徑


# DeepSeek API配置
DEEPSEEK_API_KEY = os.environ.get('DEEPSEEK_API_KEY', 'xxx')




# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-@-4cc$)_$_&protcmr1&&n8-zs!uhk3kdlr^zegw78)m!htq1*'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True # 如果要部署要改为False

# ALLOWED_HOSTS = [https://www.monkey-papa.com] # 如果部署换为这个，后端地址，没有域名就是ip＋端口号
ALLOWED_HOSTS = [
    '192.168.31.211:8000', #rk3568
    '192.168.31.211', #rk3568    
    '192.168.0.1:8000', #rk3568
    '192.168.0.1', #rk3568       
    
    '.cpolar.top',#cpolar
    '.cpolar.cn',#cpolar
    '.org',#cpolar
    'localhost',
    'localhost:8000',      # 包含端口
    '127.0.0.1',
    '127.0.0.1:8000',      # 包含端口
    '.ngrok-free.app',     # ngrok 域名
    '.ngrok-free.dev',         

]


CSRF_TRUSTED_ORIGINS = [
    "https://2501b345.r25.cpolar.top",   # 当前有效的域名
    "http://2501b345.r25.cpolar.top",   # 当前有效的域名
]






#20260729 信任crsf


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "corsheaders",
    'appone.apps.ApponeConfig',
    'user.apps.UserConfig',

    'blog.apps.BlogConfig',    # 新增博客应用 ← 推荐这种方式
    'survey.apps.SurveyConfig',    # 新增問卷应用 ← 推荐这种方式
    'godot.apps.GodotConfig',    # 新增博客应用 ← 推荐这种方式

    'rest_framework',
    'rest_framework.authtoken',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',  #20260729 屏蔽csrf驗證
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'luntan.urls'






#模板會進入app文件夾下templates下尋找
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': []
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        #deepseek 要求屏蔽解決token認證問題
        #'rest_framework.permissions.IsAuthenticated',
        'rest_framework.permissions.AllowAny',  # 允许所有访问
    ]
}


WSGI_APPLICATION = 'luntan.wsgi.application'

# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'WGodot',  # 数据库名
        'USER': 'igodot',
        'PASSWORD': 'fang1937', # 密码
        'HOST': '127.0.0.1',
        'PORT': '3306',
    }
}

# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_TZ = False

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# 跨域设置第三步骤:跨域设置
CORS_ALLOW_CREDENTIALS = True  # 解决跨域
CORS_ORIGIN_ALLOW_ALL = True  # 解决跨域


# 跨域设置第三步骤:允许的请求头，不能用*，要写具体的请求头，不然Vue会跨域失败，在这里坑了我好久好久MD
CORS_ALLOW_HEADERS = (
    'x-requested-with',
    'content-type',
    'accept',
    'origin',
    'authorization',
    'x-csrftoken'
)

CORS_ALLOW_METHODS = (
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
    'VIEW',
)




