# Generated by Django 5.2.6 on 2025-11-12 17:03

import django.core.serializers.json
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='问卷标题')),
                ('description', models.TextField(blank=True, verbose_name='问卷描述')),
                ('questions', models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder, verbose_name='问题配置')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('active', '进行中'), ('closed', '已结束')], default='draft', max_length=10, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
            ],
            options={
                'verbose_name': '调查问卷',
                'verbose_name_plural': '调查问卷',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SurveyAnswerAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_responses', models.IntegerField(default=0, verbose_name='总回答数')),
                ('answer_statistics', models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, verbose_name='回答统计')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='最后更新')),
                ('survey', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='survey.survey', verbose_name='问卷')),
            ],
            options={
                'verbose_name': '问卷分析',
                'verbose_name_plural': '问卷分析',
            },
        ),
        migrations.CreateModel(
            name='SurveyResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='用户IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='用户代理')),
                ('answers', models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder, verbose_name='回答数据')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='提交时间')),
                ('is_anonymous', models.BooleanField(default=False, verbose_name='匿名提交')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='survey.survey', verbose_name='问卷')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '问卷回答',
                'verbose_name_plural': '问卷回答',
                'ordering': ['-submitted_at'],
                'unique_together': {('survey', 'user')},
            },
        ),
    ]
