# Generated by Django 5.2.6 on 2025-11-13 19:37

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='answer_data',
            field=models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True, verbose_name='答案数据'),
        ),
        migrations.AddField(
            model_name='survey',
            name='has_answer_file',
            field=models.BooleanField(default=False, verbose_name='是否有答案文件'),
        ),
    ]
