# Generated by Django 5.2.6 on 2025-11-14 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_survey_answer_data_survey_has_answer_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyresponse',
            name='ai_comment',
            field=models.TextField(blank=True, verbose_name='AI评语'),
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='ai_evaluated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='AI评估时间'),
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='ai_score',
            field=models.FloatField(blank=True, null=True, verbose_name='AI评分'),
        ),
    ]
