# Generated by Django 5.2.6 on 2025-11-14 13:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_surveyresponse_ai_comment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyresponse',
            name='code_generated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='序列号生成时间'),
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='code_used',
            field=models.BooleanField(default=False, verbose_name='序列号是否已使用'),
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='registration_code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='注册序列号'),
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='used_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='使用时间'),
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='used_by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_registration_codes', to=settings.AUTH_USER_MODEL, verbose_name='使用用户'),
        ),
    ]
